[build]
  environment = { NODE_VERSION = "18" }
  command = "npm install && npm run build"
  publish = "public"
  functions = "netlify/functions"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
