[build]
  command = "npm install"
  publish = "public"
  environment = { NODE_VERSION = "14.17.0" }

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
