[build]
  environment = { NODE_VERSION = "18" }
  command = "npm install && npm run build"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
