[build]
  command = "npm install && npm run build"
  publish = "public"
  environment = { NODE_VERSION = "14.x" }

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
