[build]
  command = "nvm install 18 && nvm use 18 && npm install && npm run build"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
